import { supabaseAdmin, unwrap } from '@/lib/db/supabase-client';
import {
  DEFAULT_SETTINGS,
  MASTER_ADMIN_EMAIL,
  type AdminSettings,
  type LocalAnswer,
  type LocalBacktest,
  type LocalCertificate,
  type LocalCourse,
  type LocalDatabase,
  type LocalDisclaimerAcceptance,
  type LocalDisclaimerVersion,
  type LocalEnrollment,
  type LocalFaq,
  type LocalLesson,
  type LocalLessonProgress,
  type LocalMessage,
  type LocalModule,
  type LocalPasswordReset,
  type LocalPayment,
  type LocalPaymentMethod,
  type LocalProfile,
  type LocalQuestion,
  type LocalReview,
  type LocalTest,
  type LocalTranslation,
  type LocalTestAttempt,
  type LocalXpTransaction,
} from '@/lib/local-db';
import type { Database } from '@/lib/db/types';
import {
  backtestFromRow,
  backtestToRow,
  defined,
  journalFromRow,
  journalToRow,
  notificationFromRow,
  notificationToRow,
  settingsFromRow,
} from '@/lib/db/mappers';

/**
 * PostgreSQL backend (TZ §28).
 *
 * Mirrors the JSON store's contract exactly so the two are interchangeable —
 * the E2E suite runs against the local adapter and covers this one's semantics
 * by construction. Ids are always generated by the database, never by the app.
 */

const sb = () => supabaseAdmin();
const rows = <T>(data: unknown): T[] => (Array.isArray(data) ? (data as T[]) : []);
const first = <T>(data: unknown): T | null => (Array.isArray(data) && data.length ? (data[0] as T) : null);

/** What a PostgREST query resolves to. */
type QueryResult = { data: unknown; error: { message: string; code?: string } | null };

/**
 * The subset of the PostgREST builder this adapter uses. Declaring it exactly
 * keeps the query helpers typed without leaking `any` through every call site.
 */
interface Query extends PromiseLike<QueryResult> {
  eq(column: string, value: unknown): Query;
  neq(column: string, value: unknown): Query;
  lt(column: string, value: unknown): Query;
  in(column: string, values: readonly unknown[]): Query;
  ilike(column: string, pattern: string): Query;
  or(filter: string): Query;
  order(column: string, options?: { ascending?: boolean }): Query;
  limit(count: number): Query;
}

const from = (table: string): Query => sb().from(table).select('*') as unknown as Query;

/** Reads never insert; a missing row is null, not an error. */
async function selectOne<T>(table: string, build: (q: Query) => Query, ctx: string): Promise<T | null> {
  return first<T>(unwrap(await build(from(table)).limit(1), ctx));
}

async function selectMany<T>(table: string, build: (q: Query) => Query, ctx: string): Promise<T[]> {
  return rows<T>(unwrap(await build(from(table)), ctx));
}

async function insertOne<T>(table: string, row: Record<string, unknown>, ctx: string): Promise<T> {
  const data = unwrap(await sb().from(table).insert(defined(row)).select('*').single(), ctx);
  return data as T;
}

async function updateOne<T>(table: string, id: string, row: Record<string, unknown>, ctx: string): Promise<T> {
  const data = unwrap(await sb().from(table).update(defined(row)).eq('id', id).select('*').single(), ctx);
  return data as T;
}

async function deleteById(table: string, id: string, ctx: string): Promise<boolean> {
  const data = unwrap(await sb().from(table).delete().eq('id', id).select('id'), ctx);
  return rows(data).length > 0;
}

// ─── Settings ────────────────────────────────────────────────────────────────

async function readSettings(): Promise<AdminSettings> {
  const row = await selectOne<Record<string, unknown>>('platform_settings', (q) => q, 'getSettings');
  return settingsFromRow(row, DEFAULT_SETTINGS);
}

// ─── Translations ────────────────────────────────────────────────────────────
// One model shape, three SQL tables — each keyed by the row it translates.

const TRANSLATION_TABLE: Record<LocalTranslation['entity'], { table: string; fk: string }> = {
  course: { table: 'course_translations', fk: 'course_id' },
  module: { table: 'module_translations', fk: 'module_id' },
  lesson: { table: 'lesson_translations', fk: 'lesson_id' },
};

function translationFromRow(entity: LocalTranslation['entity'], row: Record<string, unknown>): LocalTranslation {
  const { fk } = TRANSLATION_TABLE[entity];
  return {
    id: String(row.id ?? ''),
    entity,
    entity_id: String(row[fk] ?? ''),
    locale: row.locale === 'en' ? 'en' : 'ru',
    title: (row.title as string | null) ?? null,
    short_description: (row.short_description as string | null) ?? null,
    description: (row.description as string | null) ?? null,
    summary: (row.summary as string | null) ?? null,
    key_terms: (row.key_terms as LocalTranslation['key_terms']) ?? null,
    updated_at: String(row.updated_at ?? ''),
  };
}

/** Only the columns that table actually has — the shapes differ per entity. */
function translationToRow(t: Partial<LocalTranslation> & { entity: LocalTranslation['entity'] }): Record<string, unknown> {
  const row: Record<string, unknown> = {};
  if (t.title !== undefined) row.title = t.title;
  if (t.description !== undefined) row.description = t.description;
  if (t.entity !== 'module' && t.short_description !== undefined) row.short_description = t.short_description;
  if (t.entity === 'lesson') {
    if (t.summary !== undefined) row.summary = t.summary;
    if (t.key_terms !== undefined) row.key_terms = t.key_terms;
  }
  return row;
}

// ─── Lesson materials (TZ §11, §28) ──────────────────────────────────────────
// Stored in their own ordered table; the model still sees one array per lesson.

type MaterialRow = { lesson_id: string; title: string; url: string; type: string; order_index: number };

async function attachMaterials<T extends LocalLesson>(lessons: T[]): Promise<T[]> {
  if (!lessons.length) return lessons;

  const rows = await selectMany<MaterialRow>(
    'lesson_materials',
    (q) => q.in('lesson_id', lessons.map((l) => l.id)).order('order_index'),
    'lessonMaterials'
  );

  const byLesson = new Map<string, LocalLesson['materials']>();
  for (const row of rows) {
    const list = byLesson.get(row.lesson_id) || [];
    list.push({ title: row.title, url: row.url, type: row.type });
    byLesson.set(row.lesson_id, list);
  }

  return lessons.map((lesson) => ({ ...lesson, materials: byLesson.get(lesson.id) || [] }));
}

/** Replaces a lesson's material list; absent means "leave as is". */
async function writeMaterials(lessonId: string, materials: LocalLesson['materials']) {
  if (materials === undefined) return;

  unwrap(
    await sb().from('lesson_materials').delete().eq('lesson_id', lessonId).select('id'),
    'lessonMaterials:clear'
  );
  if (!materials.length) return;

  unwrap(
    await sb()
      .from('lesson_materials')
      .insert(
        materials.map((m, index) => ({
          lesson_id: lessonId,
          title: m.title,
          url: m.url,
          type: m.type || 'file',
          order_index: index + 1,
        }))
      )
      .select('id'),
    'lessonMaterials:insert'
  );
}

export const supabaseAdapter: Database = {
  async getSettings() {
    return readSettings();
  },

  async saveSettings(patch) {
    unwrap(
      await sb().from('platform_settings').update(defined({ ...patch })).eq('id', true).select('*'),
      'saveSettings'
    );
    return readSettings();
  },

  // ─── Profiles ──────────────────────────────────────────────────────────────

  async getProfiles() {
    return selectMany<LocalProfile>('profiles', (q) => q.order('created_at'), 'getProfiles');
  },

  async getProfile(idOrEmail) {
    if (!idOrEmail) return null;
    const byId = await selectOne<LocalProfile>('profiles', (q) => q.eq('id', idOrEmail), 'getProfile').catch(
      () => null
    );
    if (byId) return byId;
    return selectOne<LocalProfile>(
      'profiles',
      (q) => q.ilike('email', idOrEmail),
      'getProfile:email'
    );
  },

  async saveProfile(profile) {
    const existing = profile.id
      ? await selectOne<LocalProfile>('profiles', (q) => q.eq('id', profile.id), 'saveProfile:id')
      : profile.email
        ? await selectOne<LocalProfile>('profiles', (q) => q.ilike('email', profile.email!), 'saveProfile:email')
        : null;

    if (existing) {
      const { id: _ignored, ...patch } = profile;
      return updateOne<LocalProfile>('profiles', existing.id, patch, 'saveProfile:update');
    }

    const email = (profile.email || '').toLowerCase();
    return insertOne<LocalProfile>(
      'profiles',
      {
        ...profile,
        email,
        full_name: profile.full_name || 'Yangi Treyder',
        role: profile.role || (email === MASTER_ADMIN_EMAIL ? 'admin' : 'student'),
        level: profile.level || 'Beginner',
        xp: profile.xp ?? 0,
        language: profile.language || 'uz',
        theme: profile.theme || 'dark',
      },
      'saveProfile:insert'
    );
  },

  async deleteProfile(idOrEmail) {
    const profile = await supabaseAdapter.getProfile(idOrEmail);
    if (!profile) return false;
    // The master admin account is never deletable.
    if (profile.email?.toLowerCase() === MASTER_ADMIN_EMAIL) return false;
    // Every dependent row cascades via ON DELETE CASCADE.
    return deleteById('profiles', profile.id, 'deleteProfile');
  },

  async touchProfile(userId) {
    unwrap(
      await sb().from('profiles').update({ last_active_at: new Date().toISOString() }).eq('id', userId).select('id'),
      'touchProfile'
    );
  },

  // ─── Courses ───────────────────────────────────────────────────────────────

  async getCourses() {
    return selectMany<LocalCourse>('courses', (q) => q.order('order_index'), 'getCourses');
  },

  async getCourse(idOrSlug) {
    if (!idOrSlug) return null;
    const bySlug = await selectOne<LocalCourse>('courses', (q) => q.eq('slug', idOrSlug), 'getCourse:slug');
    if (bySlug) return bySlug;
    return selectOne<LocalCourse>('courses', (q) => q.eq('id', idOrSlug), 'getCourse:id').catch(() => null);
  },

  async saveCourse(course) {
    const existing = course.id
      ? await selectOne<LocalCourse>('courses', (q) => q.eq('id', course.id), 'saveCourse:id')
      : course.slug
        ? await selectOne<LocalCourse>('courses', (q) => q.eq('slug', course.slug!), 'saveCourse:slug')
        : null;

    if (existing) {
      const { id: _ignored, ...patch } = course;
      return updateOne<LocalCourse>('courses', existing.id, patch, 'saveCourse:update');
    }
    return insertOne<LocalCourse>('courses', { ...course }, 'saveCourse:insert');
  },

  async deleteCourse(id) {
    return deleteById('courses', id, 'deleteCourse');
  },

  // ─── Modules ───────────────────────────────────────────────────────────────

  async getModules(courseId) {
    return selectMany<LocalModule>(
      'modules',
      (q) => (courseId ? q.eq('course_id', courseId) : q).order('order_index'),
      'getModules'
    );
  },

  async getModule(id) {
    if (!id) return null;
    return selectOne<LocalModule>('modules', (q) => q.eq('id', id), 'getModule').catch(() => null);
  },

  async saveModule(module) {
    if (module.id) {
      const { id: _ignored, ...patch } = module;
      return updateOne<LocalModule>('modules', module.id, patch, 'saveModule:update');
    }
    return insertOne<LocalModule>('modules', { ...module }, 'saveModule:insert');
  },

  async deleteModule(id) {
    return deleteById('modules', id, 'deleteModule');
  },

  // ─── Lessons ───────────────────────────────────────────────────────────────

  async getLessons(moduleId) {
    const lessons = await selectMany<LocalLesson>(
      'lessons',
      (q) => (moduleId ? q.eq('module_id', moduleId) : q).order('order_index'),
      'getLessons'
    );
    return attachMaterials(lessons);
  },

  async getLesson(id) {
    if (!id) return null;
    const lesson = await selectOne<LocalLesson>('lessons', (q) => q.eq('id', id), 'getLesson').catch(() => null);
    if (!lesson) return null;
    return (await attachMaterials([lesson]))[0];
  },

  async getCourseLessons(courseId) {
    const modules = await supabaseAdapter.getModules(courseId);
    if (!modules.length) return [];
    const ids = modules.map((m) => m.id);
    const all = await selectMany<LocalLesson>(
      'lessons',
      (q) => q.in('module_id', ids).order('order_index'),
      'getCourseLessons'
    );
    // Keep course order: modules first, lessons within each.
    return modules.flatMap((m) => all.filter((l) => l.module_id === m.id));
  },

  async saveLesson(lesson) {
    const { materials, ...rest } = lesson;

    if (lesson.id) {
      const { id: _ignored, ...patch } = rest;
      const saved = await updateOne<LocalLesson>('lessons', lesson.id, patch, 'saveLesson:update');
      await writeMaterials(saved.id, materials);
      return (await attachMaterials([saved]))[0];
    }

    const created = await insertOne<LocalLesson>('lessons', { ...rest }, 'saveLesson:insert');
    await writeMaterials(created.id, materials);
    return (await attachMaterials([created]))[0];
  },

  async deleteLesson(id) {
    return deleteById('lessons', id, 'deleteLesson');
  },

  // ─── Tests ─────────────────────────────────────────────────────────────────

  async getTests() {
    return selectMany<LocalTest>('tests', (q) => q.order('created_at'), 'getTests');
  },

  async getTest(id) {
    if (!id) return null;
    return selectOne<LocalTest>('tests', (q) => q.eq('id', id), 'getTest').catch(() => null);
  },

  async getTestByLesson(lessonId) {
    return selectOne<LocalTest>('tests', (q) => q.eq('lesson_id', lessonId), 'getTestByLesson');
  },

  async saveTest(test) {
    const existing = test.id
      ? await selectOne<LocalTest>('tests', (q) => q.eq('id', test.id), 'saveTest:id')
      : test.lesson_id
        ? await selectOne<LocalTest>('tests', (q) => q.eq('lesson_id', test.lesson_id!), 'saveTest:lesson')
        : null;

    if (existing) {
      const { id: _ignored, ...patch } = test;
      return updateOne<LocalTest>('tests', existing.id, patch, 'saveTest:update');
    }
    return insertOne<LocalTest>(
      'tests',
      { ...test, passing_score: test.passing_score ?? DEFAULT_SETTINGS.passing_score },
      'saveTest:insert'
    );
  },

  async deleteTest(id) {
    return deleteById('tests', id, 'deleteTest');
  },

  async getTestQuestions(testId) {
    const questions = await selectMany<LocalQuestion>(
      'questions',
      (q) => q.eq('test_id', testId).order('order_index'),
      'getTestQuestions'
    );
    if (!questions.length) return [];

    const answers = await selectMany<LocalAnswer>(
      'answers',
      (q) => q.in('question_id', questions.map((x) => x.id)).order('order_index'),
      'getTestQuestions:answers'
    );

    return questions.map((question) => ({
      ...question,
      answers: answers.filter((a) => a.question_id === question.id),
    }));
  },

  /** Replaces the whole question set; ON DELETE CASCADE removes old answers. */
  async replaceTestQuestions(testId, questions) {
    unwrap(await sb().from('questions').delete().eq('test_id', testId).select('id'), 'replaceTestQuestions:clear');

    for (const [index, q] of questions.entries()) {
      const created = await insertOne<LocalQuestion>(
        'questions',
        {
          test_id: testId,
          question: q.question,
          order_index: index + 1,
          points: q.points ?? 1,
          multiple: q.multiple ?? false,
        },
        'replaceTestQuestions:question'
      );

      if (q.answers?.length) {
        unwrap(
          await sb()
            .from('answers')
            .insert(
              q.answers.map((a, i) => ({
                question_id: created.id,
                answer: a.answer,
                is_correct: Boolean(a.is_correct),
                order_index: i + 1,
              }))
            )
            .select('id'),
          'replaceTestQuestions:answers'
        );
      }
    }

    return questions.length;
  },

  // ─── Enrollments ───────────────────────────────────────────────────────────

  async getEnrollments(userId) {
    return selectMany<LocalEnrollment>(
      'enrollments',
      (q) => (userId ? q.eq('user_id', userId) : q).order('purchased_at', { ascending: false }),
      'getEnrollments'
    );
  },

  async saveEnrollment(enrollment) {
    const existing =
      enrollment.user_id && enrollment.course_id
        ? await selectOne<LocalEnrollment>(
            'enrollments',
            (q) => q.eq('user_id', enrollment.user_id!).eq('course_id', enrollment.course_id!),
            'saveEnrollment:lookup'
          )
        : null;

    if (existing) {
      const { id: _ignored, ...patch } = enrollment;
      return updateOne<LocalEnrollment>('enrollments', existing.id, patch, 'saveEnrollment:update');
    }
    return insertOne<LocalEnrollment>(
      'enrollments',
      { ...enrollment, status: enrollment.status || 'active', source: enrollment.source || 'manual' },
      'saveEnrollment:insert'
    );
  },

  async hasEnrollment(userId, courseId) {
    if (!userId || !courseId) return false;
    const row = await selectOne<LocalEnrollment>(
      'enrollments',
      (q) => q.eq('user_id', userId).eq('course_id', courseId).eq('status', 'active'),
      'hasEnrollment'
    );
    return Boolean(row);
  },

  async revokeEnrollment(userId, courseId) {
    const data = unwrap(
      await sb()
        .from('enrollments')
        .update({ status: 'revoked' })
        .eq('user_id', userId)
        .eq('course_id', courseId)
        .select('id'),
      'revokeEnrollment'
    );
    return rows(data).length > 0;
  },

  // ─── Lesson progress ───────────────────────────────────────────────────────

  async getProgress(userId, lessonId) {
    return selectMany<LocalLessonProgress>(
      'lesson_progress',
      (q) => (lessonId ? q.eq('user_id', userId).eq('lesson_id', lessonId) : q.eq('user_id', userId)),
      'getProgress'
    );
  },

  async getLessonProgress(userId, lessonId) {
    return selectOne<LocalLessonProgress>(
      'lesson_progress',
      (q) => q.eq('user_id', userId).eq('lesson_id', lessonId),
      'getLessonProgress'
    );
  },

  async saveProgress(progress) {
    const previous = await supabaseAdapter.getLessonProgress(progress.user_id, progress.lesson_id);

    if (previous) {
      const { id: _ignored, ...patch } = progress;
      return updateOne<LocalLessonProgress>(
        'lesson_progress',
        previous.id,
        {
          ...patch,
          // Watch progress only ever moves forward.
          watched_seconds: Math.max(previous.watched_seconds, progress.watched_seconds ?? 0),
          watch_percentage: Math.max(previous.watch_percentage, progress.watch_percentage ?? 0),
          video_completed: previous.video_completed || progress.video_completed || false,
        },
        'saveProgress:update'
      );
    }

    return insertOne<LocalLessonProgress>('lesson_progress', { ...progress }, 'saveProgress:insert');
  },

  // ─── Test attempts ─────────────────────────────────────────────────────────

  async getAttempts(userId, testId) {
    return selectMany<LocalTestAttempt>(
      'test_attempts',
      (q) => (testId ? q.eq('user_id', userId).eq('test_id', testId) : q.eq('user_id', userId)),
      'getAttempts'
    );
  },

  async getAllAttempts() {
    return selectMany<LocalTestAttempt>('test_attempts', (q) => q, 'getAllAttempts');
  },

  async saveAttempt(attempt) {
    return insertOne<LocalTestAttempt>('test_attempts', { ...attempt }, 'saveAttempt');
  },

  // ─── XP ────────────────────────────────────────────────────────────────────

  async getXpTransactions(userId) {
    return selectMany<LocalXpTransaction>(
      'xp_transactions',
      (q) => q.eq('user_id', userId).order('created_at', { ascending: false }),
      'getXpTransactions'
    );
  },

  /**
   * Award XP at most once per (user, source, reference).
   * The unique index on those columns makes a double award impossible even
   * under a race; a duplicate insert simply grants nothing.
   */
  async awardXp(userId, amount, reason, source, referenceId) {
    const profile = await supabaseAdapter.getProfile(userId);
    if (!profile || amount <= 0) return { granted: 0, totalXp: profile?.xp ?? 0 };

    const insert = await sb()
      .from('xp_transactions')
      .insert({ user_id: userId, amount, reason, source, reference_id: referenceId ?? null })
      .select('id');

    if (insert.error) {
      // 23505 = unique violation: this reward was already collected.
      if ((insert.error as { code?: string }).code === '23505') {
        return { granted: 0, totalXp: profile.xp ?? 0 };
      }
      throw new Error(`[supabase] awardXp: ${insert.error.message}`);
    }

    const totalXp = (profile.xp ?? 0) + amount;
    await updateOne<LocalProfile>('profiles', userId, { xp: totalXp }, 'awardXp:profile');
    return { granted: amount, totalXp };
  },

  // ─── Payments ──────────────────────────────────────────────────────────────

  async getPayments(userId) {
    const list = await selectMany<LocalPayment>(
      'payments',
      (q) => (userId ? q.eq('user_id', userId) : q).order('created_at', { ascending: false }),
      'getPayments'
    );
    return attachPaymentRelations(list);
  },

  async getPayment(idOrOrderId) {
    if (!idOrOrderId) return null;
    const byOrder = await selectOne<LocalPayment>(
      'payments',
      (q) => q.eq('order_id', idOrOrderId),
      'getPayment:order'
    );
    const found =
      byOrder ||
      (await selectOne<LocalPayment>('payments', (q) => q.eq('id', idOrOrderId), 'getPayment:id').catch(
        () => null
      ));
    if (!found) return null;
    return (await attachPaymentRelations([found]))[0];
  },

  async savePayment(paymentData) {
    const existing =
      (paymentData.id
        ? await selectOne<LocalPayment>('payments', (q) => q.eq('id', paymentData.id), 'savePayment:id').catch(
            () => null
          )
        : null) ||
      (paymentData.order_id
        ? await selectOne<LocalPayment>(
            'payments',
            (q) => q.eq('order_id', paymentData.order_id!),
            'savePayment:order'
          )
        : null);

    // Relations are read-only decorations; never write them back.
    const { courses: _c, profiles: _p, id: _id, ...writable } = paymentData;

    if (existing) {
      return updateOne<LocalPayment>('payments', existing.id, writable, 'savePayment:update');
    }

    const settings = await readSettings();
    const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, '');
    const count = unwrap(
      await sb().from('payments').select('id', { count: 'exact', head: true }),
      'savePayment:count'
    );
    const sequence = String(((count as unknown as number) || 0) + 1).padStart(6, '0');

    return insertOne<LocalPayment>(
      'payments',
      {
        ...writable,
        order_id: paymentData.order_id || `NE-${stamp}-${sequence}`,
        currency: paymentData.currency || settings.currency,
        provider: paymentData.provider || 'manual',
        status: paymentData.status || 'pending',
        expires_at:
          paymentData.expires_at ||
          new Date(Date.now() + settings.payment_window_minutes * 60 * 1000).toISOString(),
      },
      'savePayment:insert'
    );
  },

  async approvePayment(idOrOrderId, approvedBy) {
    const payment = await supabaseAdapter.getPayment(idOrOrderId);
    if (!payment) return null;
    return updateOne<LocalPayment>(
      'payments',
      payment.id,
      {
        status: 'approved',
        approved_at: new Date().toISOString(),
        paid_at: new Date().toISOString(),
        approved_by: approvedBy ?? null,
      },
      'approvePayment'
    );
  },

  async rejectPayment(idOrOrderId, reason, rejectedBy) {
    const payment = await supabaseAdapter.getPayment(idOrOrderId);
    if (!payment) return null;
    return updateOne<LocalPayment>(
      'payments',
      payment.id,
      {
        status: 'rejected',
        rejected_at: new Date().toISOString(),
        rejection_reason: reason,
        approved_by: rejectedBy ?? null,
      },
      'rejectPayment'
    );
  },

  async cancelPayment(idOrOrderId) {
    const payment = await supabaseAdapter.getPayment(idOrOrderId);
    if (!payment) return null;
    return updateOne<LocalPayment>(
      'payments',
      payment.id,
      { status: 'cancelled', cancelled_at: new Date().toISOString() },
      'cancelPayment'
    );
  },

  /** Expires unpaid orders whose 15-minute window has elapsed (TZ §19). */
  async expireStalePayments() {
    const data = unwrap(
      await sb()
        .from('payments')
        .update({ status: 'expired' })
        .in('status', ['pending', 'receipt_submitted'])
        .lt('expires_at', new Date().toISOString())
        .select('id'),
      'expireStalePayments'
    );
    return rows(data).length;
  },

  // ─── Notifications ─────────────────────────────────────────────────────────

  async getNotifications(userId) {
    const list = await selectMany<Record<string, unknown>>(
      'notifications',
      (q) => q.or(`user_id.eq.${userId},user_id.is.null`).order('created_at', { ascending: false }),
      'getNotifications'
    );
    return list.map(notificationFromRow);
  },

  async addNotification(n) {
    const created = await insertOne<Record<string, unknown>>(
      'notifications',
      notificationToRow({ ...n, read: n.read ?? false }),
      'addNotification'
    );
    return notificationFromRow(created);
  },

  async markNotificationRead(userId, notificationId) {
    let query = sb().from('notifications').update({ read: true }).eq('user_id', userId);
    if (notificationId) query = query.eq('id', notificationId);
    const data = unwrap(await query.select('id'), 'markNotificationRead');
    return rows(data).length;
  },

  // ─── Journal ───────────────────────────────────────────────────────────────

  async getJournal(userId) {
    const list = await selectMany<Record<string, unknown>>(
      'journals',
      (q) => q.eq('user_id', userId).order('trade_date', { ascending: false }),
      'getJournal'
    );
    return list.map(journalFromRow);
  },

  async saveJournalTrade(userId, trade) {
    if (trade.id) {
      const updated = await updateOne<Record<string, unknown>>(
        'journals',
        trade.id,
        journalToRow({ ...trade, user_id: userId }),
        'saveJournalTrade:update'
      );
      return journalFromRow(updated);
    }
    const created = await insertOne<Record<string, unknown>>(
      'journals',
      journalToRow({ ...trade, user_id: userId }),
      'saveJournalTrade:insert'
    );
    return journalFromRow(created);
  },

  async deleteJournalTrade(userId, tradeId) {
    const data = unwrap(
      await sb().from('journals').delete().eq('id', tradeId).eq('user_id', userId).select('id'),
      'deleteJournalTrade'
    );
    return rows(data).length > 0;
  },

  // ─── Backtests ─────────────────────────────────────────────────────────────

  async getBacktests(userId) {
    const list = await selectMany<Record<string, unknown>>(
      'backtests',
      (q) => q.eq('user_id', userId).order('created_at', { ascending: false }),
      'getBacktests'
    );
    return list.map(backtestFromRow);
  },

  async saveBacktest(userId, bt) {
    const wins = bt.wins ?? 0;
    const total = bt.totalTrades ?? 0;
    const derived = {
      ...bt,
      losses: bt.losses ?? Math.max(0, total - wins),
      winRate: bt.winRate ?? (total ? Math.round((wins / total) * 100) : 0),
    };

    if (bt.id) {
      const updated = await updateOne<Record<string, unknown>>(
        'backtests',
        bt.id,
        backtestToRow({ ...derived, user_id: userId }),
        'saveBacktest:update'
      );
      return backtestFromRow(updated);
    }
    const created = await insertOne<Record<string, unknown>>(
      'backtests',
      backtestToRow({ ...derived, user_id: userId }),
      'saveBacktest:insert'
    );
    return backtestFromRow(created);
  },

  async deleteBacktest(userId, id) {
    const data = unwrap(
      await sb().from('backtests').delete().eq('id', id).eq('user_id', userId).select('id'),
      'deleteBacktest'
    );
    return rows(data).length > 0;
  },

  // ─── Certificates ──────────────────────────────────────────────────────────

  async getCertificates(userId) {
    return selectMany<LocalCertificate>(
      'certificates',
      (q) => (userId ? q.eq('user_id', userId) : q).order('issued_at', { ascending: false }),
      'getCertificates'
    );
  },

  async getCertificateById(certificateId) {
    return selectOne<LocalCertificate>(
      'certificates',
      (q) => q.eq('certificate_id', certificateId),
      'getCertificateById'
    );
  },

  async issueCertificate(cert) {
    return insertOne<LocalCertificate>('certificates', { ...cert }, 'issueCertificate');
  },

  async nextCertificateSequence() {
    const count = unwrap(
      await sb().from('certificates').select('id', { count: 'exact', head: true }),
      'nextCertificateSequence'
    );
    return ((count as unknown as number) || 0) + 1;
  },

  // ─── Risk disclaimer ───────────────────────────────────────────────────────

  async getActiveDisclaimer() {
    const active = await selectOne<LocalDisclaimerVersion>(
      'risk_disclaimer_versions',
      (q) => q.eq('is_active', true),
      'getActiveDisclaimer'
    );
    if (active) return active;

    const latest = await selectOne<LocalDisclaimerVersion>(
      'risk_disclaimer_versions',
      (q) => q.order('created_at', { ascending: false }),
      'getActiveDisclaimer:latest'
    );
    if (latest) return latest;

    throw new Error('[supabase] no risk disclaimer version exists — run supabase/schema.sql seed');
  },

  async getDisclaimerVersions() {
    return selectMany<LocalDisclaimerVersion>(
      'risk_disclaimer_versions',
      (q) => q.order('created_at', { ascending: false }),
      'getDisclaimerVersions'
    );
  },

  async saveDisclaimerVersion(version) {
    if (version.is_active) {
      unwrap(
        await sb().from('risk_disclaimer_versions').update({ is_active: false }).eq('is_active', true).select('id'),
        'saveDisclaimerVersion:deactivate'
      );
    }

    const existing = version.version
      ? await selectOne<LocalDisclaimerVersion>(
          'risk_disclaimer_versions',
          (q) => q.eq('version', version.version!),
          'saveDisclaimerVersion:lookup'
        )
      : null;

    if (existing) {
      const { id: _ignored, ...patch } = version;
      return updateOne<LocalDisclaimerVersion>(
        'risk_disclaimer_versions',
        existing.id,
        patch,
        'saveDisclaimerVersion:update'
      );
    }
    return insertOne<LocalDisclaimerVersion>('risk_disclaimer_versions', { ...version }, 'saveDisclaimerVersion');
  },

  async recordDisclaimerAcceptance(a) {
    const existing = await selectOne<LocalDisclaimerAcceptance>(
      'risk_disclaimer_acceptances',
      (q) => q.eq('user_id', a.user_id).eq('version', a.version),
      'recordDisclaimerAcceptance:lookup'
    );
    if (existing) return existing;
    return insertOne<LocalDisclaimerAcceptance>('risk_disclaimer_acceptances', { ...a }, 'recordDisclaimerAcceptance');
  },

  async hasAcceptedDisclaimer(userId, version) {
    const target = version || (await supabaseAdapter.getActiveDisclaimer()).version;
    const row = await selectOne<LocalDisclaimerAcceptance>(
      'risk_disclaimer_acceptances',
      (q) => q.eq('user_id', userId).eq('version', target),
      'hasAcceptedDisclaimer'
    );
    return Boolean(row);
  },

  async getAcceptances(userId) {
    return selectMany<LocalDisclaimerAcceptance>(
      'risk_disclaimer_acceptances',
      (q) => (userId ? q.eq('user_id', userId) : q).order('accepted_at'),
      'getAcceptances'
    );
  },

  // ─── Payment methods ───────────────────────────────────────────────────────

  async getPaymentMethods(onlyEnabled = false) {
    return selectMany<LocalPaymentMethod>(
      'payment_methods',
      (q) => (onlyEnabled ? q.eq('enabled', true) : q).order('order_index'),
      'getPaymentMethods'
    );
  },

  async savePaymentMethod(method) {
    if (method.id) {
      const { id: _ignored, ...patch } = method;
      return updateOne<LocalPaymentMethod>('payment_methods', method.id, patch, 'savePaymentMethod:update');
    }
    return insertOne<LocalPaymentMethod>('payment_methods', { ...method }, 'savePaymentMethod:insert');
  },

  async deletePaymentMethod(id) {
    return deleteById('payment_methods', id, 'deletePaymentMethod');
  },

  // ─── Messages ──────────────────────────────────────────────────────────────

  async getMessages(userId) {
    return selectMany<LocalMessage>(
      'messages',
      (q) => q.eq('user_id', userId).order('created_at'),
      'getMessages'
    );
  },

  async getAllMessageThreads() {
    const all = await selectMany<LocalMessage>('messages', (q) => q.order('created_at'), 'getAllMessageThreads');
    const byUser = new Map<string, LocalMessage[]>();
    for (const m of all) {
      if (!byUser.has(m.user_id)) byUser.set(m.user_id, []);
      byUser.get(m.user_id)!.push(m);
    }
    return [...byUser.entries()].map(([user_id, list]) => ({
      user_id,
      last: list[list.length - 1],
      unread: list.filter((m) => m.sender === 'user' && !m.read).length,
    }));
  },

  async saveMessage(msg) {
    return insertOne<LocalMessage>('messages', { ...msg, read: msg.read ?? false }, 'saveMessage');
  },

  // ─── Reviews ───────────────────────────────────────────────────────────────

  async getReviews(options = {}) {
    return selectMany<LocalReview>(
      'reviews',
      (q) => {
        let query = q;
        if (options.approvedOnly) query = query.eq('approved', true);
        if (options.courseId) query = query.eq('course_id', options.courseId);
        return query.order('created_at', { ascending: false });
      },
      'getReviews'
    );
  },

  async getUserReview(userId, courseId) {
    return selectOne<LocalReview>(
      'reviews',
      (q) => q.eq('user_id', userId).eq('course_id', courseId),
      'getUserReview'
    );
  },

  async saveReview(review) {
    const existing = await supabaseAdapter.getUserReview(review.user_id, review.course_id);
    if (existing) {
      const { id: _ignored, ...patch } = review;
      return updateOne<LocalReview>('reviews', existing.id, patch, 'saveReview:update');
    }
    return insertOne<LocalReview>('reviews', { ...review }, 'saveReview:insert');
  },

  async setReviewApproval(id, approved) {
    const data = unwrap(
      await sb().from('reviews').update({ approved }).eq('id', id).select('id'),
      'setReviewApproval'
    );
    return rows(data).length > 0;
  },

  async deleteReview(id) {
    return deleteById('reviews', id, 'deleteReview');
  },

  // ─── FAQ ───────────────────────────────────────────────────────────────────

  async getFaqs(publishedOnly = false) {
    return selectMany<LocalFaq>(
      'faqs',
      (q) => (publishedOnly ? q.eq('published', true) : q).order('order_index'),
      'getFaqs'
    );
  },

  async saveFaq(faq) {
    if (faq.id) {
      const { id: _ignored, ...patch } = faq;
      return updateOne<LocalFaq>('faqs', faq.id, patch, 'saveFaq:update');
    }
    return insertOne<LocalFaq>('faqs', { ...faq }, 'saveFaq:insert');
  },

  async deleteFaq(id) {
    return deleteById('faqs', id, 'deleteFaq');
  },

  // ─── Content translations (TZ §25) ─────────────────────────────────────────

  async getTranslations(entity, locale) {
    const kinds = entity ? [entity] : (['course', 'module', 'lesson'] as LocalTranslation['entity'][]);

    const results = await Promise.all(
      kinds.map(async (kind) => {
        const { table } = TRANSLATION_TABLE[kind];
        const list = await selectMany<Record<string, unknown>>(
          table,
          (q) => (locale ? q.eq('locale', locale) : q),
          `getTranslations:${kind}`
        );
        return list.map((row) => translationFromRow(kind, row));
      })
    );

    return results.flat();
  },

  async getTranslation(entity, entityId, locale) {
    const { table, fk } = TRANSLATION_TABLE[entity];
    const row = await selectOne<Record<string, unknown>>(
      table,
      (q) => q.eq(fk, entityId).eq('locale', locale),
      `getTranslation:${entity}`
    );
    return row ? translationFromRow(entity, row) : null;
  },

  async saveTranslation(translation) {
    const { table, fk } = TRANSLATION_TABLE[translation.entity];
    const existing = await selectOne<Record<string, unknown>>(
      table,
      (q) => q.eq(fk, translation.entity_id).eq('locale', translation.locale),
      `saveTranslation:${translation.entity}`
    );

    const patch = translationToRow(translation);

    if (existing) {
      const updated = await updateOne<Record<string, unknown>>(
        table,
        String(existing.id),
        patch,
        `saveTranslation:${translation.entity}:update`
      );
      return translationFromRow(translation.entity, updated);
    }

    const created = await insertOne<Record<string, unknown>>(
      table,
      { ...patch, [fk]: translation.entity_id, locale: translation.locale },
      `saveTranslation:${translation.entity}:insert`
    );
    return translationFromRow(translation.entity, created);
  },

  async deleteTranslation(entity, entityId, locale) {
    const { table, fk } = TRANSLATION_TABLE[entity];
    const data = unwrap(
      await sb().from(table).delete().eq(fk, entityId).eq('locale', locale).select('id'),
      `deleteTranslation:${entity}`
    );
    return rows(data).length > 0;
  },

  // ─── Password resets ───────────────────────────────────────────────────────

  async createPasswordReset(userId, email) {
    return insertOne<LocalPasswordReset>(
      'password_resets',
      { user_id: userId, email: email.toLowerCase(), status: 'pending' },
      'createPasswordReset'
    );
  },

  async getPasswordReset(id) {
    return selectOne<LocalPasswordReset>('password_resets', (q) => q.eq('id', id), 'getPasswordReset').catch(
      () => null
    );
  },

  async approvePasswordReset(id, tokenHash, ttlMinutes) {
    const data = unwrap(
      await sb()
        .from('password_resets')
        .update({
          status: 'approved',
          token_hash: tokenHash,
          approved_at: new Date().toISOString(),
          expires_at: new Date(Date.now() + ttlMinutes * 60 * 1000).toISOString(),
        })
        .eq('id', id)
        .eq('status', 'pending')
        .select('*'),
      'approvePasswordReset'
    );
    return first<LocalPasswordReset>(data);
  },

  async rejectPasswordReset(id) {
    const data = unwrap(
      await sb()
        .from('password_resets')
        .update({ status: 'rejected' })
        .eq('id', id)
        .eq('status', 'pending')
        .select('id'),
      'rejectPasswordReset'
    );
    return rows(data).length > 0;
  },

  async findValidPasswordReset(tokenHash) {
    const row = await selectOne<LocalPasswordReset>(
      'password_resets',
      (q) => q.eq('token_hash', tokenHash).eq('status', 'approved'),
      'findValidPasswordReset'
    );
    if (!row) return null;
    if (!row.expires_at || new Date(row.expires_at).getTime() < Date.now()) return null;
    return row;
  },

  /** Burns the token so a reset link works exactly once. */
  async consumePasswordReset(id) {
    const data = unwrap(
      await sb()
        .from('password_resets')
        .update({ status: 'used', used_at: new Date().toISOString(), token_hash: null })
        .eq('id', id)
        .eq('status', 'approved')
        .select('id'),
      'consumePasswordReset'
    );
    return rows(data).length > 0;
  },

  // ─── Activity log ──────────────────────────────────────────────────────────

  async logActivity(userId, action, metadata) {
    unwrap(
      await sb()
        .from('activity_logs')
        .insert({ user_id: userId || null, action, metadata: metadata ?? {} })
        .select('id'),
      'logActivity'
    );
  },

  async getActivity(userId, limit = 50) {
    return selectMany(
      'activity_logs',
      (q) => (userId ? q.eq('user_id', userId) : q).order('created_at', { ascending: false }).limit(limit),
      'getActivity'
    );
  },

  // ─── Aggregates ────────────────────────────────────────────────────────────

  async getStats() {
    const [payments, profiles, courses, modules, lessons, attempts, certificates, progress] = await Promise.all([
      selectMany<LocalPayment>('payments', (q) => q, 'getStats:payments'),
      selectMany<LocalProfile>('profiles', (q) => q, 'getStats:profiles'),
      selectMany<LocalCourse>('courses', (q) => q, 'getStats:courses'),
      selectMany<LocalModule>('modules', (q) => q, 'getStats:modules'),
      selectMany<LocalLesson>('lessons', (q) => q, 'getStats:lessons'),
      selectMany<LocalTestAttempt>('test_attempts', (q) => q, 'getStats:attempts'),
      selectMany<LocalCertificate>('certificates', (q) => q, 'getStats:certificates'),
      selectMany<LocalLessonProgress>('lesson_progress', (q) => q, 'getStats:progress'),
    ]);

    const approved = payments.filter((p) => p.status === 'approved');
    const students = profiles.filter((p) => p.role === 'student');
    const paidUserIds = new Set(approved.map((p) => p.user_id));
    const dayAgo = Date.now() - 24 * 60 * 60 * 1000;

    return {
      totalUsers: students.length,
      totalProfiles: profiles.length,
      totalRevenue: approved.reduce((sum, p) => sum + (p.amount || 0), 0),
      pendingReceiptsCount: payments.filter((p) => p.status === 'receipt_submitted').length,
      approvedCount: approved.length,
      rejectedCount: payments.filter((p) => p.status === 'rejected').length,
      courseCount: courses.length,
      moduleCount: modules.length,
      lessonCount: lessons.length,
      paidUsersCount: paidUserIds.size,
      registeredOnlyCount: Math.max(0, students.length - paidUserIds.size),
      activeUsersCount: profiles.filter(
        (p) => p.last_active_at && new Date(p.last_active_at).getTime() > dayAgo
      ).length,
      testAttempts: attempts.length,
      testPassRate: attempts.length
        ? Math.round((attempts.filter((a) => a.passed).length / attempts.length) * 100)
        : 0,
      certificatesIssued: certificates.filter((c) => !c.revoked).length,
      completedLessons: progress.filter((p) => p.completed).length,
    };
  },

  /**
   * Whole-database snapshot.
   *
   * Only the admin analytics screens use this; it is a full table scan per
   * table, so it must never be called on a request-hot path.
   */
  async raw(): Promise<LocalDatabase> {
    const [
      courses, modules, lessons, tests, questions, answers, payments, profiles,
      enrollments, lesson_progress, test_attempts, xp_transactions, notifications,
      journals, backtests, certificates, disclaimer_versions, disclaimer_acceptances,
      payment_methods, activity_logs, messages, reviews, faqs, password_resets, settings,
    ] = await Promise.all([
      selectMany<LocalCourse>('courses', (q) => q.order('order_index'), 'raw:courses'),
      selectMany<LocalModule>('modules', (q) => q.order('order_index'), 'raw:modules'),
      selectMany<LocalLesson>('lessons', (q) => q.order('order_index'), 'raw:lessons').then(attachMaterials),
      selectMany<LocalTest>('tests', (q) => q, 'raw:tests'),
      selectMany<LocalQuestion>('questions', (q) => q.order('order_index'), 'raw:questions'),
      selectMany<LocalAnswer>('answers', (q) => q.order('order_index'), 'raw:answers'),
      selectMany<LocalPayment>('payments', (q) => q.order('created_at', { ascending: false }), 'raw:payments'),
      selectMany<LocalProfile>('profiles', (q) => q, 'raw:profiles'),
      selectMany<LocalEnrollment>('enrollments', (q) => q, 'raw:enrollments'),
      selectMany<LocalLessonProgress>('lesson_progress', (q) => q, 'raw:lesson_progress'),
      selectMany<LocalTestAttempt>('test_attempts', (q) => q, 'raw:test_attempts'),
      selectMany<LocalXpTransaction>('xp_transactions', (q) => q, 'raw:xp_transactions'),
      selectMany<Record<string, unknown>>('notifications', (q) => q.order('created_at', { ascending: false }), 'raw:notifications'),
      selectMany<Record<string, unknown>>('journals', (q) => q, 'raw:journals'),
      selectMany<Record<string, unknown>>('backtests', (q) => q, 'raw:backtests'),
      selectMany<LocalCertificate>('certificates', (q) => q, 'raw:certificates'),
      selectMany<LocalDisclaimerVersion>('risk_disclaimer_versions', (q) => q, 'raw:disclaimer_versions'),
      selectMany<LocalDisclaimerAcceptance>('risk_disclaimer_acceptances', (q) => q, 'raw:acceptances'),
      selectMany<LocalPaymentMethod>('payment_methods', (q) => q.order('order_index'), 'raw:payment_methods'),
      selectMany('activity_logs', (q) => q.order('created_at', { ascending: false }).limit(500), 'raw:activity_logs'),
      selectMany<LocalMessage>('messages', (q) => q, 'raw:messages'),
      selectMany<LocalReview>('reviews', (q) => q, 'raw:reviews'),
      selectMany<LocalFaq>('faqs', (q) => q.order('order_index'), 'raw:faqs'),
      selectMany<LocalPasswordReset>('password_resets', (q) => q, 'raw:password_resets'),
      readSettings(),
    ]);

    return {
      courses, modules, lessons, tests, questions, answers, payments, profiles,
      enrollments, lesson_progress, test_attempts, xp_transactions,
      notifications: notifications.map(notificationFromRow),
      journals: journals.map(journalFromRow),
      backtests: backtests.map(backtestFromRow),
      certificates, disclaimer_versions, disclaimer_acceptances, payment_methods,
      activity_logs, messages, reviews, faqs, password_resets, settings,
    } as LocalDatabase;
  },

  /** Destructive maintenance helper: keeps only the master admin account. */
  async resetUsersToAdminOnly() {
    const admin = await selectOne<LocalProfile>(
      'profiles',
      (q) => q.ilike('email', MASTER_ADMIN_EMAIL),
      'resetUsers:admin'
    );

    let query = sb().from('profiles').delete();
    query = admin ? query.neq('id', admin.id) : query.neq('id', '00000000-0000-0000-0000-000000000000');
    unwrap(await query.select('id'), 'resetUsersToAdminOnly');

    return admin ? [admin] : [];
  },

  /** Idempotent catalogue seed; never overwrites an admin's edits. */
  async seedCatalog(seed) {
    let courses = 0;
    let modules = 0;
    let lessons = 0;

    for (const course of seed.courses) {
      const existing = await selectOne<LocalCourse>('courses', (q) => q.eq('id', course.id), 'seed:course').catch(
        () => null
      );
      if (!existing) {
        unwrap(await sb().from('courses').insert(course).select('id'), 'seed:insertCourse');
        courses++;
      }
    }

    for (const seedModule of seed.modules) {
      const existing = await selectOne<LocalModule>(
        'modules',
        (q) => q.eq('id', seedModule.id),
        'seed:module'
      ).catch(() => null);
      if (!existing) {
        unwrap(await sb().from('modules').insert(seedModule).select('id'), 'seed:insertModule');
        modules++;
      }
    }

    for (const lesson of seed.lessons) {
      const existing = await selectOne<LocalLesson>('lessons', (q) => q.eq('id', lesson.id), 'seed:lesson').catch(
        () => null
      );
      if (!existing) {
        unwrap(await sb().from('lessons').insert(lesson).select('id'), 'seed:insertLesson');
        lessons++;
      }
    }

    return { courses, modules, lessons };
  },
};

/** Decorates payments with their course and buyer, as the model expects. */
async function attachPaymentRelations(list: LocalPayment[]): Promise<LocalPayment[]> {
  if (!list.length) return [];

  const courseIds = [...new Set(list.map((p) => p.course_id).filter(Boolean))];
  const userIds = [...new Set(list.map((p) => p.user_id).filter(Boolean))];

  const [courses, profiles] = await Promise.all([
    courseIds.length
      ? selectMany<LocalCourse>('courses', (q) => q.in('id', courseIds), 'payments:courses')
      : Promise.resolve([]),
    userIds.length
      ? selectMany<LocalProfile>('profiles', (q) => q.in('id', userIds), 'payments:profiles')
      : Promise.resolve([]),
  ]);

  const courseById = new Map(courses.map((c) => [c.id, c]));
  const profileById = new Map(profiles.map((p) => [p.id, p]));

  return list.map((p) => ({
    ...p,
    courses: courseById.get(p.course_id) || null,
    profiles: profileById.get(p.user_id) || null,
  }));
}
